// Sample destination data for Nepal-focused recommendation system
const destinations = [
    {
        id: 1,
        name: "Kathmandu Valley",
        description: "The cultural and historical heart of Nepal with UNESCO World Heritage sites, ancient temples, and vibrant markets.",
        image: "https://public.youware.com/users-website-assets/prod/1e6b8fef-19d2-424c-ac94-d8f2e7904a8e/15273c37665c4b8896924a8825bdbe3c.jpg",
        mood: ["cultural", "social", "adventurous"],
        season: ["spring", "fall", "winter"],
        climate: ["mild", "cool"],
        activityLevel: ["moderate", "active"],
        tripLength: ["short", "medium"],
        budget: ["budget", "moderate"],
        interests: ["culture", "food", "history"]
    },
    {
        id: 2,
        name: "Pokhara",
        description: "Scenic lakeside city with stunning views of the Annapurna mountain range, perfect for relaxation and adventure sports.",
        image: "https://source.unsplash.com/random/800x600/?pokhara,nepal",
        mood: ["relaxed", "adventurous", "romantic"],
        season: ["spring", "fall", "winter"],
        climate: ["mild", "warm"],
        activityLevel: ["relaxed", "moderate", "active"],
        tripLength: ["short", "medium"],
        budget: ["budget", "moderate", "luxury"],
        interests: ["nature", "adventure", "relaxation"]
    },
    {
        id: 3,
        name: "Everest Base Camp Trek",
        description: "The iconic trek to the base of the world's highest mountain, offering breathtaking mountain scenery and cultural encounters.",
        image: "https://source.unsplash.com/random/800x600/?everest,nepal",
        mood: ["adventurous"],
        season: ["spring", "fall"],
        climate: ["cool", "cold"],
        activityLevel: ["active", "adventurous"],
        tripLength: ["medium", "long"],
        budget: ["moderate", "luxury"],
        interests: ["nature", "adventure", "trekking"]
    },
    {
        id: 4,
        name: "Annapurna Circuit",
        description: "One of the world's most diverse treks, passing through varied landscapes from subtropical forests to high alpine terrain.",
        image: "https://public.youware.com/users-website-assets/prod/1e6b8fef-19d2-424c-ac94-d8f2e7904a8e/8de5cfbab62048a39275e86d76b98c67.jpg",
        mood: ["adventurous", "cultural"],
        season: ["spring", "fall"],
        climate: ["cool", "cold"],
        activityLevel: ["active", "adventurous"],
        tripLength: ["medium", "long"],
        budget: ["moderate", "luxury"],
        interests: ["nature", "adventure", "trekking", "culture"]
    },
    {
        id: 5,
        name: "Chitwan National Park",
        description: "Nepal's first national park known for its wildlife safaris, where you can spot rhinos, tigers, and various bird species.",
        image: "https://public.youware.com/users-website-assets/prod/1e6b8fef-19d2-424c-ac94-d8f2e7904a8e/3125d7be3233402bae4e8a3e7c4d9947.jpg",
        mood: ["adventurous", "relaxed"],
        season: ["winter", "spring", "fall"],
        climate: ["warm", "tropical"],
        activityLevel: ["moderate", "active"],
        tripLength: ["short", "medium"],
        budget: ["moderate", "luxury"],
        interests: ["nature", "adventure", "wildlife"]
    },
    {
        id: 6,
        name: "Lumbini",
        description: "The birthplace of Buddha with sacred gardens, monasteries, and archeological sites of significant spiritual importance.",
        image: "https://source.unsplash.com/random/800x600/?lumbini,nepal",
        mood: ["cultural", "relaxed", "spiritual"],
        season: ["winter", "spring", "fall"],
        climate: ["warm", "mild"],
        activityLevel: ["relaxed"],
        tripLength: ["short", "medium"],
        budget: ["budget", "moderate"],
        interests: ["culture", "spirituality", "history"]
    },
    {
        id: 7,
        name: "Nagarkot",
        description: "A hillside village near Kathmandu offering spectacular sunrise and sunset views of the Himalayas.",
        image: "https://source.unsplash.com/random/800x600/?nagarkot,nepal",
        mood: ["romantic", "relaxed"],
        season: ["spring", "fall", "winter"],
        climate: ["cool", "mild"],
        activityLevel: ["relaxed", "moderate"],
        tripLength: ["weekend", "short"],
        budget: ["moderate", "luxury"],
        interests: ["nature", "relaxation", "views"]
    },
    {
        id: 8,
        name: "Patan (Lalitpur)",
        description: "Ancient city of arts and architecture with the famous Durbar Square, traditional crafts, and beautiful temples.",
        image: "https://source.unsplash.com/random/800x600/?patan,nepal",
        mood: ["cultural", "social"],
        season: ["spring", "fall", "winter"],
        climate: ["mild", "cool"],
        activityLevel: ["moderate"],
        tripLength: ["short"],
        budget: ["budget", "moderate"],
        interests: ["culture", "history", "art"]
    },
    {
        id: 9,
        name: "Bhaktapur",
        description: "Well-preserved medieval city with traditional Newari architecture, pottery squares, and religious festivals.",
        image: "https://source.unsplash.com/random/800x600/?bhaktapur,nepal",
        mood: ["cultural", "social"],
        season: ["spring", "fall", "winter"],
        climate: ["mild", "cool"],
        activityLevel: ["moderate"],
        tripLength: ["short"],
        budget: ["budget", "moderate"],
        interests: ["culture", "history", "art"]
    },
    {
        id: 10,
        name: "Langtang Valley",
        description: "Less crowded trekking region close to Kathmandu with stunning mountain vistas, glaciers, and Tamang culture.",
        image: "https://source.unsplash.com/random/800x600/?langtang,nepal",
        mood: ["adventurous", "cultural"],
        season: ["spring", "fall"],
        climate: ["cool", "cold"],
        activityLevel: ["active", "adventurous"],
        tripLength: ["medium"],
        budget: ["moderate"],
        interests: ["nature", "adventure", "trekking", "culture"]
    },
    {
        id: 11,
        name: "Rara Lake",
        description: "Remote and pristine alpine lake in western Nepal, surrounded by mountains and forests, perfect for wilderness exploration.",
        image: "https://source.unsplash.com/random/800x600/?rara,lake,nepal",
        mood: ["adventurous", "relaxed"],
        season: ["spring", "summer", "fall"],
        climate: ["cool"],
        activityLevel: ["moderate", "active"],
        tripLength: ["medium"],
        budget: ["moderate"],
        interests: ["nature", "adventure", "off-the-beaten-path"]
    },
    {
        id: 12,
        name: "Upper Mustang",
        description: "Remote desert-like region with ancient Tibetan culture, cave monasteries, and dramatic cliff-side villages.",
        image: "https://source.unsplash.com/random/800x600/?mustang,nepal",
        mood: ["adventurous", "cultural"],
        season: ["summer", "fall"],
        climate: ["cool", "dry"],
        activityLevel: ["active", "adventurous"],
        tripLength: ["medium", "long"],
        budget: ["luxury"],
        interests: ["culture", "adventure", "history", "off-the-beaten-path"]
    },
    {
        id: 13,
        name: "Bandipur",
        description: "Charming hilltop town with preserved Newari architecture, offering panoramic mountain views and cultural experiences.",
        image: "https://source.unsplash.com/random/800x600/?bandipur,nepal",
        mood: ["cultural", "relaxed", "romantic"],
        season: ["spring", "fall", "winter"],
        climate: ["mild"],
        activityLevel: ["relaxed", "moderate"],
        tripLength: ["short"],
        budget: ["budget", "moderate"],
        interests: ["culture", "relaxation", "views"]
    },
    {
        id: 14,
        name: "Gokyo Lakes",
        description: "Series of stunning turquoise alpine lakes in the Everest region, offering an alternative to the main EBC route.",
        image: "https://source.unsplash.com/random/800x600/?gokyo,nepal",
        mood: ["adventurous"],
        season: ["spring", "fall"],
        climate: ["cool", "cold"],
        activityLevel: ["active", "adventurous"],
        tripLength: ["medium", "long"],
        budget: ["moderate", "luxury"],
        interests: ["nature", "adventure", "trekking"]
    },
    {
        id: 15,
        name: "Bardia National Park",
        description: "Remote wilderness area offering wildlife safaris with fewer crowds than Chitwan, known for tigers and elephants.",
        image: "https://source.unsplash.com/random/800x600/?bardia,nepal",
        mood: ["adventurous", "relaxed"],
        season: ["winter", "spring"],
        climate: ["warm"],
        activityLevel: ["moderate", "active"],
        tripLength: ["medium"],
        budget: ["moderate", "luxury"],
        interests: ["nature", "wildlife", "off-the-beaten-path"]
    }
];